---

- name: 'Install Extra Packages for Enterprise Linux (EPEL)'
  yum: name='epel-release' state='present'

- name: 'Install zip'
  yum: name='zip' state='installed'

- name: 'Install OpenVPN'
  yum: name='openvpn' state='present'

- name: 'Install IPtables service'
  yum: name='iptables' state='present'

- name: 'Ensure group "nogroup" is present'
  group: name='nogroup' state='present'

- name: 'Generate server config'
  include: 'server_config.yml'

- name: 'Generate client config for DEVOPS'
  include: client_config.yml clients='{{openvpn_clients}}'

- name: 'Persist ip forwarding'
  sysctl: name='net.ipv4.ip_forward' value=1 state='present' sysctl_set=yes reload=yes ignoreerrors=yes

- name: 'Clear iptables rules'
  command: 'iptables -t nat -F'

- name: 'Add iptables rules'
  shell: 'iptables -t nat -A POSTROUTING -s {{ item }} -o eth0 -j MASQUERADE'
  with_items:
   - '{{ cidr_vpn }}'
   - '{{ cidr_vpc }}'

- name: 'Save iptables'
  shell: 'service iptables save'

- name: 'Start openvpn now (systemd)'
  service: name='{{ openvpn_service_name }}' state='started' enabled='yes'