
- name: download etcd
  get_url: url=https://github.com/coreos/etcd/releases/download/v3.0.3/etcd-v3.0.3-linux-amd64.tar.gz dest=/tmp/etcd.tar.gz

- name: untar etcd
  unarchive: src=/tmp/etcd.tar.gz dest=/tmp copy=no

- name: execute etcd
  shell: nohup /tmp/etcd-v3.0.3-linux-amd64/etcd --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://0.0.0.0:2379 &
  become: true
