- name: Ansible provisioner
  hosts: all
  roles:
  - { role: cert, tags: ['etcd','k8s-controller','k8s-worker']}
  - { role: etcd, tags: ['etcd']}
  - { role: k8s-controller, tags: ['k8s-controller']}
