- hosts: tag_Name_eneko_kubernetes_etcd
  tags: ['all','etcd']
  roles:
  - { role: cert}
  - { role: etcd}

- hosts: tag_Name_eneko_kubernetes_controllers
  tags: ['all','k8s-controller']
  roles:
  - { role: cert}
  - { role: k8s-controller}

- hosts: tag_Name_eneko_kubernetes_workers
  tags: ['all','k8s-worker']
  roles:
  - { role: cert}
  - { role: k8s-worker}

- hosts: localhost
  tags: ['all','localhost']
  roles:
  - { role: k8s-dns}

- hosts: localhost
  tags: ['all','test']
  roles:
    - { role: smoke-test}



